# Generated by Django 4.2.2 on 2023-06-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=8)),
                ("race_id", models.CharField(max_length=8)),
                ("ticket_id", models.CharField(max_length=8)),
                ("event_title", models.TextField()),
                ("race_title", models.TextField()),
                ("ticket_title", models.TextField()),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "unique_together": {("event_id", "race_id", "ticket_id")},
            },
        ),
    ]
