# Generated by Django 4.2.2 on 2023-06-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0002_alter_ticket_unique_together_ticket_dataset_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
